# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5c67a841e60be083916f1a38e0d1e37902ba04017f65afbe82525f1abff18f1f4239509fb79a3538d518e0e64efd18d9f24d66394168e16bffe5988525b3596

test:
  secret_key_base: 791f0bd133a810e7934d696e7e7a1df6bb4ff9231a43014c597515b557d03b85f10d0efe82c5d6727add656b2a5b1e4dfcafb8892b7cc951efce52a885624a7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
